### ISSUE TITLE
Initialize repository

### ISSUE THREAD

**Issue by SirThxAlot** [SirThxAlot/STA-BALOO#1]
**Version:** 0.0.3-0001

In order to start developing we will need an initial commit, which will initialize the repository and creates the 'origin-master' branch. This commit should provide the common files of a modern webapplication, e.g. README.md, License and a gitignore file, in order to exclude other files or paths from further commits.

## Subtasks

- [x] **README.md**  
      - [x] Create new _README.md_ file in the _root_ directory of the application  
      - [x] Introduce and describe the application  
      - [x] Add a list with important links of the project and its third party modules  
      - [x] Describe how to install the application  
      - [x] Describe how to setup the webserver  
      - [x] Add additional informations for Windows users  
- [x] **License**  
      - [x] Create new _license_ directory, in order to collect the licenses of the application and its third party modules  
      - [x] Create new _license/gnu-gpl-v3.license.txt_ license  
      - [x] Create new _license/sta-baloo.license.txt_ license  
- [x] **Gitignore**  
      - [x] Create new _.gitignore_ file, in order to ignore files or paths from further commits  
      - [x] Ignore the generated project files of the Zend Studio IDE, from further commits (.gitignore)
