### ISSUE TITLE
Error-Handler

### ISSUE THREAD

**Issue by SirThxAlot** [SirThxAlot/STA-BALOO#10]
**Version:** 0.11.3-0010
**Branch:**  feature/001

The first feature of the application will be an error handler, in order to provide features to handle errors and exceptions. Im going to use the common.php file, in order to setup the PHP-Error-Handler and implement the Error-Handler-Service which will provide the errror handling features.

## Related Links

 * [PHP-Manual: Error Handling and Logging](http://php.net/manual/en/book.errorfunc.php)
 * [Simple logging of ZF2 exceptions, by Rob Allen](http://akrabat.com/zend-framework-2/simple-logging-of-zf2-exceptions/)

## Subtasks

- [ ] Setup `error_handler_service` in _common.php_
- [ ] Translate errors into exceptions in _common.php_ [->](http://php.net/manual/en/class.errorexception.php)
- [ ] Create new `Error-Handling-Service` and inject `Zend\Log` into it
- [ ] Create new service method: `logErrorsToFile()`, in order to log errors into a file
- [ ] Create new listener: `Application\Listener`, in order to listen events on application layer
    - [ ] Catch `dispatch.error` event, in order to log the error into the error logfile
