### ISSUE TITLE
Composer-Support

### ISSUE THREAD

**Issue by SirThxAlot** [SirThxAlot/STA-BALOO#2]
**Version:** 0.2.3-0002 
**Branch:** skeleton/application

Use [Composer](https://github.com/SirThxAlot/STA-BALOO/wiki/Composer), in order to install the dependent libraries of the application, this tool allows you to easily install packages provided by [Packagist](https://packagist.org/).

## Subtasks

- [x] **Composer**  
      - [x] Download Composer, using command line interface and PHP  
      - [x] Add Composer-Support in Zend Studio IDE, in order to generate _composer.json_  
      - [x] Require min. PHP-Version **5.4.0**, in _composer.json_  
      - [x] Require the Zend Framework **2.3.***, from `zendframework/zendframework`, in _composer.json_  
      - [x] Run the Composer installation  
- [x] **Further**  
      - [x] Ignore the generated _vendor_ directory and its content from further commits (.gitignore)  
      - [x] Copy and rename the license of the Zend Framework 2
