### ISSUE TITLE
Composer-Support

### ISSUE THREAD

**Issue by SirThxAlot** [SirThxAlot/STA-BALOO#2]
Use [Composer](https://github.com/SirThxAlot/STA-BALOO/wiki/About-Composer), in order to install the dependent libraries of the application, this tool allows you to easily install packages provided by [Packagist](https://packagist.org/).

**Version:** 0.1.3-0002

## Tasks

- [x] **Composer**  
      - [x] Download Composer, using command line interface and PHP  
      - [x] Add Composer-Support in Zend Studio IDE, in order to generate _composer.json_  
      - [x] Require min. PHP-Version **5.4.0**, in _composer.json_  
      - [x] Require the Zend Framework **2.3.***, from `zendframework/zendframework`, in _composer.json_  
      - [x] Run the Composer installation  
- [x] **Further**  
      - [x] Ignore the generated _vendor_ directory and its content from further commits (.gitignore)  
      - [x] Remove advice in _README.md_ about the log files [FIX]
      - [x] Copy and rename the license of the Zend Framework 2
