### ISSUE TITLE
Front-Controller

### ISSUE THREAD

**Issue by SirThxAlot** [SirThxAlot/STA-BALOO#3]
Create the Front-Controller of the application, in order to provide the HTTP-Requests. 
At this point the application, will throw a `RuntimeException()`, because the Front-Controller 
tries to load an non existing file: _common.php_.

**Version:** 0.2.3-0003 [instable]

## Tasks

- [x] **Preparation**  
      - [x] Create new _public/.htaccess_ file, in order to redirect the requests to the Front-Controller  
      - [x] Create new _public/index.php_ file, in order to provide the Front-Controller of the application  
- [x] **Front-Controller**  
      - [x] Add DocBlock comment, in order to describe the file  
      - [x] Define constant `ZF2_TIMESTAMP`, in order to calculate the elapsed runtime  
      - [x] Define constant `APP_ROOT`, in order to return the absolute path to the root directory of the application  
      - [x] Change current directory to `APP_ROOT` constant  
      - [x] Decline static file requests send by command line interface  
      - [x] Require _common.php_, if file exits otherwise throw `RuntimeException()`  
      - [x] Initialize and run the `Zend\Mvc\Application`  
- [x] **Webserver-Setup**  
      - [x] `mod_rewrite` module, in order to use the _public/.htaccess_ file (optional)  

### Example: `ZF2_TIMESTAMP`

    define('ZF2_TIMESTAMP', microtime(true));

### Example: .htaccess file

    RewriteEngine On
    # The following rule tells Apache that if the requested filename
    # exists, simply serve it.
    RewriteCond %{REQUEST_FILENAME} -s [OR]
    RewriteCond %{REQUEST_FILENAME} -l [OR]
    RewriteCond %{REQUEST_FILENAME} -d
    RewriteRule ^.*$ - [NC,L]
    # The following rewrites all other queries to index.php. The 
    # condition ensures that if you are using Apache aliases to do
    # mass virtual hosting, the base path will be prepended to 
    # allow proper resolution of the index.php file; it will work
    # in non-aliased environments as well, providing a safe, one-size 
    # fits all solution.
    RewriteCond %{REQUEST_URI}::$1 ^(/.+)(.+)::\2$
    RewriteRule ^(.*) - [E=BASE:%1]
    RewriteRule ^(.*)$ %{ENV:BASE}index.php [NC,L]
