### ISSUE TITLE
Front-Controller

### ISSUE THREAD

**Issue by SirThxAlot** [SirThxAlot/STA-BALOO#3]
**Version:** 0.3.3-0003 [instable]
**Branch:** skeleton/application

The Front-Controller is the first instance of any HTTP-Request to the application. It provides the requests to the forseen action handler, requires the common files and initialize the application.

## Subtasks

- [x] **Preparation**  
      - [x] Create new _public_ directory, in order to store the public files of the application  
      - [x] Create new _public/.htaccess_ file, in order to redirect the requests to the Front-Controller  
      - [x] Create new _public/index.php_ file, in order to provide the Front-Controller of the application  
- [x] **Front-Controller**  
      - [x] Add DocBlock comment, in order to describe the file  
      - [x] Define constant `ZF2_TIME_START`, in order to calculate the elapsed runtime  
      - [x] Define constant `APP_ROOT`, in order to return the absolute path to the root directory of the application  
      - [x] Change current directory to `APP_ROOT` constant  
      - [x] Decline static file requests send by command line interface  
      - [x] Require _common.php_, if file exits otherwise throw `RuntimeException()`  
      - [x] Initialize and run the `Zend\Mvc\Application`  
- [x] **Webserver-Setup**  
      - [x] `mod_rewrite` module, in order to use the _public/.htaccess_ file (optional)  

### Microtime Zend Framework 2

    define('ZF2_TIME_START', microtime(true));

### .htaccess

    RewriteEngine On
    # The following rule tells Apache that if the requested filename
    # exists, simply serve it.
    RewriteCond %{REQUEST_FILENAME} -s [OR]
    RewriteCond %{REQUEST_FILENAME} -l [OR]
    RewriteCond %{REQUEST_FILENAME} -d
    RewriteRule ^.*$ - [NC,L]
    # The following rewrites all other queries to index.php. The 
    # condition ensures that if you are using Apache aliases to do
    # mass virtual hosting, the base path will be prepended to 
    # allow proper resolution of the index.php file; it will work
    # in non-aliased environments as well, providing a safe, one-size 
    # fits all solution.
    RewriteCond %{REQUEST_URI}::$1 ^(/.+)(.+)::\2$
    RewriteRule ^(.*) - [E=BASE:%1]
    RewriteRule ^(.*)$ %{ENV:BASE}index.php [NC,L]
