### ISSUE TITLE
Common

### ISSUE THREAD

**Issue by SirThxAlot** [SirThxAlot/STA-BALOO#4]
**Version:** 0.4.3-0004
**Branch:** skeleton/application

The Application will need a file, in order to load the common files and prepare the application for running. If everything was setup successfully, the file will require and return the system configuration array, in order to initialize the `Zend\Mvc\Application`.

## Subtasks

- [x] Create new _common.php_ file, in order setup the application  
      - [x] Add DocBlock comment, in order to describe _common.php_  
      - [ ] Create a Closure-Function, in order to filter strings into absolute paths relative to the root directory of the application  
      - [x] Define constant `APP_ENV`, if not allready defined, use the global PHP-Variable `$APPLICATION_ENV`, in order to get the environment of the application  
      - [x] Require Composer autoloading file (_vendor/autoload.php_), in order to autload the dependent libraries installed by Composer. The application will throw a `RuntimeException()`, if the file doesn't exists  
      - [x] Require System-Configuration (_config/application.config.php_), in order to return the array, used to initialize the `Zend\Mvc\Application`. A `RuntimeException()` will be thrown if the required file doesn't exists

### Path Filter

    $filterPath = function ($path)
    {
        $filterSlashes = str_replace('/', '\\', $path); // replace slashes with backslashes
        $path = APP_ROOT . '\\' . $filterSlashes;       // set path in relation to the root directory of the application
    
        return $path;
    };

## Set Application environment

    if (defined('APP_ENV') == false) {
        if (getenv('APPLICATION_ENV') == 'development') {
            $environment = 'development';
        } else {
            $environment = 'production';
        }

        define('APP_ENV', $environment);

        unset($environment);
    }
