### ISSUE TITLE
common.php

### ISSUE THREAD

**Issue by SirThxAlot** [SirThxAlot/STA-BALOO#4]
The Front-Controller will require _common.php_, in order to setup the application and 
return the system configuration array. Since this file is missing a `RuntimeException()` 
will be thrown, now we are going to correct this, but at this stage the application 
still throws a `RuntimeException()`, because of the missing system configuration file.

**Version:** 0.3.3-0004 [instable]

## Tasks

- [ ] Create new _common.php_ file, in order setup the application  
      - [ ] Add DocBlock comment, in order to describe _common.php_  
      - [ ] Define constant `APP_ENV`, if not allready defined, use the global PHP-Variable `$APPLICATION_ENV`, in order to get the environment of the application  
      - [ ] Require Composer autoloading file (_vendor/autoload.php_), in order to autload the dependent libraries installed by Composer. The application will throw a `RuntimeException()`, if the file doesn't exists  
      - [ ] Require System-Configuration (_config/application.config.php_), in order to return the array, used to initialize the `Zend\Mvc\Application`. A `RuntimeException()` will be thrown if the required file doesn't exists
