### ISSUE TITLE
System-Configuration

### ISSUE THREAD

**Issue by SirThxAlot** [SirThxAlot/STA-BALOO#5]
**Version:** 0.4.3-0005 [instable]
**Branch:** 'skeleton/application'

Now we will need the system configuration array, in order to initialize the `Zend\Mvc\Application` 
and dummies of the module overriding configuration files.

At this point the application will throw a `RuntimeException()`, because it tries to load an non existing module namespace: `Core`.

## Main-Task

- [x] Create new file: _config/application.config.php_  
- [x] Create new file: _config/autoload/global.php_  
- [x] Create new file: _config/autoload/local.php.dist_  

## System Configuration

- [x] Set module namespaces, used in the application  
- [x] Set path to the modules, used in the application  
- [x] Set path to the module overriding configuration files   

## Module Override Configuration

- [x] Return an empty array

## Sub-Task

- [x] Ignore local module overriding configuration files, from further commits (.gitignore)
