### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by SirThxAlot** [SirThxAlot/STA-BALOO#5]
**Version:** 0.5.3-0005 [instable] 
**Branch:** skeleton/application

We are nearly done with the preparation of the application, next we will need the configuration files. We start with the system configuration array, which will be needed, in order to initialize the `Zend\Mvc\Application`. In this file I am going to declare the namespaces of the modules and where they reside for example. Last but not least, I will provide examples of the module overriding configurations (local, global).

## Subtasks

- [x] Create new _config_ and _config/autoload_ directories  
- [x] Create new _config/application.config.php_ file, in order to store the system configurations  
      - [x] Use `Core` namespace as a module  
      - [x] Define the paths to the modules (_module_ and _vendor_)  
      - [x] Define the paths to the module overriding configurations  
- [x] Create new _config/autoload/global.php_ file, in order to provide the global module override configuration  
- [x] Create new _config/autoload/local.php.dist_ file, in order to provide the local module override configuration
- [x] Ignore local module overriding conigurations from further commits (gitignore)
