### ISSUE TITLE
Core-Module

### ISSUE THREAD

**Issue by SirThxAlot** [SirThxAlot/STA-BALOO#6]
**Version:** 0.5.3-0006 [instable]
**Branch:** 'skeleton/application'

Create a skeleton module using the `Core` namespace, in order to provide the default 
module of the application.

At this point the application will throw a `RuntimeException()`, because it tries to resolve the render strategy, which isn't implemented yet.

## Main-Task

- [x] Create new file: _module/Core/Module.php_  
- [x] Create new file: _module/Core/config/module.config.php_   

## Core-Module

- [x] Define namespace: `Core`  
- [x] Create class: `Module`  
      - [x] Implement `AutoloaderProviderInterface`  
      - [x] Implement `BootstrapListenerInterface`  
      - [x] Implement `ConfigProviderInterface`    
- [x] Create public function: `onBootstrap(EventInterface $e)`  
      - [x] Get Event-Manager  
      - [x] Attach Event-Manager to Module-Route-Listener   
- [x] Create public function: `getConfig()`  
      - [x] Return required module configuration  
- [x] Create public function: `getAutoloaderConfig()`  
      - [x] Use `ClassMapAutoloader`, in order to autoload the namespaces  
      - [x] Use `StandardAutoloader`, in order to autoload the namespaces  

## Core-Module-Configuration

- [x] Return an empty configuration array

## Sub-Task

- [x] Generate */module/Core/autoload_classmap.php*
