### ISSUE TITLE
Core-Module

### ISSUE THREAD

**Issue by SirThxAlot** [SirThxAlot/STA-BALOO#6]
**Version:** 0.6.3-0006 [instable] 
**Branch:** skeleton/application

Every ZF2 Application will need at least one module, in this case it will be the Core-Module, which provides general functions of the application.

## Subtasks

- [x] Create new _module_ directory, in order to store the modules  
- [x] Create new _module/Core_ directory, in order to store the Core-Module  
- [x] Create new _module/Core/Module.php_ file, in order to provide the modules class  
- [x] Create new _module/config_ directory, in order to store the module configuration  
- [x] Create new _module/config/module.config.php_ file, in order to provide the module configuration of the Core-Module  
- [x] Generate documentation with PHPDocumentor and check the results  

## Core-Module  

- [x] Implement following namespaces:

    ```
    use Zend\ModuleManager\Feature\AutoloaderProviderInterface;
    use Zend\ModuleManager\Feature\BootstrapListenerInterface;
    use Zend\ModuleManager\Feature\ConfigProviderInterface;
    ```

- [x] Use Event-Interface instead of MVC-Event for bootstraping  

    `use Zend\EventManager\EventInterface;`

- [x] `onBootstrap()`  
      - [x] Attach event-manager to module route listener  
- [x] `getConfig()`  
- [x] `getAutoloaderConfig()`  
      - [x] Class-Map-Autoload  
      - [x] Standard-Autoload  

- [x] Generate class-map for Core-Module
