### ISSUE TITLE
Layout-View

### ISSUE THREAD

**Issue by SirThxAlot** [SirThxAlot/STA-BALOO#7]
**Version:** 0.7.3-0007
**Branch:** skeleton/application

Allrighty we allready implemented our first module (Core-Module). Now we will need a design-pattern or layout-view, in order to create a template for our websites. ZF2 allows you to use diffrent layout-views, but we will start with a single laoyut-view, where we are going to store the common parts of our page.

## Subtasks

- [x] Create new _module/Core/view/layout/_ directories, in order to store the design-pattern  
- [x] Create new _module/Core/view/layout/layout.phtml_ file, in order to provide the layout-view  
- [x] Setup view in core module configuration
