### ISSUE TITLE
Layout-View

### ISSUE THREAD

**Issue by SirThxAlot** [SirThxAlot/STA-BALOO#7]
**Version:** 0.11.3-0007 [instable]
**Branch:** 'skeleton/application'

Most sites enforce a cohesive look-and-feel which we typically call the site’s “layout”. It includes the default stylesheets and JavaScript necessary, if any, as well as the basic markup structure into which all site content will be injected. Create the default layout view of the application, in order to store the common HTML-Parts of our Webpage.

At this point the application will throw a `RuntimeException()`, because it tries to render the error page and or page not found (404) site, which doesn't exists yet.

## Main-Task

- [x] Create new file: _/module/Core/view/layout/layout.phtml_  
- [x] Create new file: _/less/theme.config.less_  
- [x] Create new file: _/less/compile/theme.less_  

## Layout-View

**Head**  
- [x] Define `headTitle()`, in order to set the title of the document  
      - [x] `setSeparator(': ')`, in order to use a colon as delimeter  
      - [x] `setAutoEscape(false)`, in order to disable the auto escaping  
- [x] Define `headMeta()`, in order to set meta tags in the head of the document  
      - [x] Append Name: `viewport` to `width=device-width, initial-scale=1.0`, in order to scale the pages on mobile devices  
      - [x] Append HTTPEquiv: `X-UA-Compatible` to `IE=edge`, in order to support the highest version of Internet Explorer  
- [x] Define `headLink()`, in order to define the stylesheets  
      - [x] Setup favicon of the webpage  
      - [x] Implement _theme.min.css_  
      - [x] Implement _bootstrap.min.css_  
      - [x] Implement _bootstrap-theme.min.css_  
- [x] Define `headScript()`, in order to provide the scripts of the application  
      - [x] Implement _custom.js_  
      - [x] Implement _bootstrap.min.js_  
      - [x] Implement _jquery.min.js_  
      - [x] Implement _respond.js_ (codition: `lt IE 9`)  
      - [x] Implement _html5shiv.js_ (condition: `lt IE 9`)  
      - [x] Implement _html5shiv-printshiv.js_ (condition: `lt IE 9`)  
      - [x] Echo `$this->doctype()` set in module configuration

**Body**  
- [x] Echo inline view: `$this->content`  
- [x] Echo inline script: `$this->inlineScript()`  

## Theme Configuration

- [x] Set `font-size` to `16px`  
- [x] Set `line-height` to `round(1.4 * @font-size, 2)`  

## Theme

- [x] Import _/less/sta-baloo.config.less_, in order to get the configurations  
- [x] Define `width: 100%; height: 100%;`, for the `html` element  

## Module-Configuration

- [x] Set `view_manager` configuration, in order to provide the layout  
      - [x] Set `doctype` to `'HTML 5'`, in `view_manager` configuration  
      - [x] Add `'layout/layout'`, in `view_manager` > `template_map`, in order to define the path to the layout view  
      - [x] Add `template_path_stack` array, in order to scan for views  

## Sub-Task

- [x] Add _favicon.ico_ to **/public/assets/img**, in order to provide the favicon  
- [x] Download and provide latest version of Twitter-Bootstrap (minified)  
- [x] Download and provide latest version of jQuery (minified)  
- [x] Download and provide latest version of HTML5Shiv (minified)  
- [x] Download and provide latest version of Respond.js  
- [x] Provide empty javascript file: _/public/assets/js/custom.js_, in order to store custom javascript  
- [x] Compile _/less/compile/theme.less_ into _/public/assets/css/theme.min.css_, using WinLess  
- [x] Ignore unsused styling files from further commits (.gitignore), but keep them on development system  
- [x] Ignore unsused script files from further commits (.gitignore), but keep them on development system  

## Links

* [HTML5shiv](https://github.com/aFarkas/html5shiv)
* [Respond.js](https://github.com/scottjehl/Respond)
* [Twitter-Bootstrap](http://getbootstrap.com/)
* [jQuery](http://jquery.com/)

**Comment by SirThxAlot** [comment]
# View-Configuration

The `view_manager` contains the setup of the application views. Most sites enforce a cohesive look-and-feel which we typically call the site’s “layout”. It includes the default stylesheets and JavaScript necessary, if any, as well as the basic markup structure into which all site content will be injected.

You will find the configuration, in order to setup the layout view in the following example:

    'view_manager' => array(
        'doctype'       => "HTML5",
        'template_map'  => array(
            'layout/layout' => dirname(__DIR__) . "/view/layout/layout.phtml",
        ),
        'template_path_stack' => array(
            dirname(__DIR__) . "/view",
        ),
    ),
