### ISSUE TITLE
Error-Views

### ISSUE THREAD

**Issue by SirThxAlot** [SirThxAlot/STA-BALOO#8]
**Version:** 0.13.3-0008
**Branch:** 'skeleton/application'

The application should show two diffrent pages, when errors occurs. One page, in order to display that an internal error occured (index) and another for page not found (404) errors. Provide these pages and configure displaying reason with the `ini_get('display_errors')`, if you run the application in your browser, you should receive the 404-Error (page not found).

## Main-Task

- [x] Create new file: _/module/Core/view/error/index.phtml  
- [x] Create new file: _/module/Core/view/error/404.phtml  

## Error-View

- [x] Copy from Zend Skeleton Application, tidy up the code and add docBlock comment  

## 404-View

- [x] Copy from Zend Skeleton Application, tidy up the code and add docBlock comment  

## Sub-Task

- [x] Setup error views in module configuration  
- [x] Setup displaying errors in module configuration  

## Snippets

**module configuration**  

        'display_not_found_reason' => ini_get('display_errors'),
        'display_exceptions'       => ini_get('display_errors'),

        'not_found_template'       => 'error/404',
        'exception_template'       => 'error/index',
