### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by SirThxAlot** [SirThxAlot/STA-BALOO#9]
**Version:** 0.14.3-0009
**Branch:** 'skeleton/application'

Finally we are able to define the Homepage of the application. Therefore I am going to setup the routing, create a controller and a view, in order to render the Homepage.

## Main-Task

- [x] Create new file: _/module/Core/view/core/index/index.phtml_  
- [x] Create new file: _/module/Core/src/Core/Controller/IndexController.php_  

## Index-Controller

- [x] Define namespace: `Core\Controller`  
- [x] Create class: `IndexController` extends `AbstractActionController`  
- [x] Create public function: `indexAction()`, in order to render the Homepage  
      - [x] Return new `ViewModel`  

## Index-View

- [x] Welcome-Title  
- [x] Short description about STA-BALOO  

## Module-Configuration

- [x] Add `core/index/index` view to `template_map`, in order to provide the view for the Homepage  
- [x] Setup routing of homepage in module configuration  
- [x] Allow subroutes from `IndexController`, e.g. /core/`$Controller$`/`$Action$`  
- [x] Invoke `Core\Controller\Index` in `controllers`, in order to provide the `IndexController`  

## Sub-Task
- [x] Run the application in Browser, in order to test it  
- [x] Create phpDocumentor documentation and check for errors
